services:
  - type: web
    name: space-station
    env: python
    buildCommand: "pip install -r requirements.txt && python init_sqlite_db.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
